### ISSUE TITLE
aws_mq_broker endpoints order

### ISSUE THREAD

**Issue by thomas-brx** [hashicorp/terraform-provider-aws#13786]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.13
AWS provider 2.66.0

### Affected Resource(s)

* aws_mq_broker

### Terraform Configuration Files

```hcl
output "ssl_endpoint" {
  value = aws_mq_broker.amq_broker.instances.0.endpoints.0
}
```

### Expected Behavior

`ssl_endpoint = "ssl://<...>:61617"`

### Actual Behavior

`ssl_endpoint = "amqp+ssl://<...>:5671"`

### Steps to Reproduce
With an existing `aws_mq_broker`, and the above output variable:

1. `terraform apply`

### Factoids
According to the [documentation](https://www.terraform.io/docs/providers/aws/r/mq_broker.html#attributes-reference), the order of the endpoints should be well defined:

> instances.0.endpoints - The broker's wire-level protocol endpoints in the following order & format referenceable e.g. as instances.0.endpoints.0 (SSL):
> * ssl://broker-id.mq.us-west-2.amazonaws.com:61617
> * amqp+ssl://broker-id.mq.us-west-2.amazonaws.com:5671
> * stomp+ssl://broker-id.mq.us-west-2.amazonaws.com:61614
> * mqtt+ssl://broker-id.mq.us-west-2.amazonaws.com:8883
> * wss://broker-id.mq.us-west-2.amazonaws.com:61619

The order seems to be defined by the order in the AWS API, which, in our case, has changed from one day to the next:
```
$ aws mq describe-broker --broker-id <broker-id> --query BrokerInstances[].Endpoints
[
    [
        "amqp+ssl://<broker-id>-1.mq.eu-west-1.amazonaws.com:5671",
        "wss://<broker-id>-1.mq.eu-west-1.amazonaws.com:61619",
        "stomp+ssl://<broker-id>-1.mq.eu-west-1.amazonaws.com:61614",
        "ssl://<broker-id>-1.mq.eu-west-1.amazonaws.com:61617",
        "mqtt+ssl://<broker-id>-1.mq.eu-west-1.amazonaws.com:8883"
    ]
]
```

### Workaround
To get a specific endpoint, the following workaround can be used:
```hcl
output "ssl_endpoint" {
  value = [for endpoint in aws_mq_broker.amq_broker.instances.0.endpoints : endpoint if length(regexall("^ssl:", endpoint)) > 0][0]
}
```

**Comment by jpenalver10** [comment]
Hello, today I could see that the order of providers has been restored? The same happens to you? It's the bugfix resolved?

Thanks

**Comment by thomas-brx** [comment]
> Hello, today I could see that the order of providers has been restored? The same happens to you? It's the bugfix resolved?
> 
> Thanks

Yes, I see the same thing - the order from AWS now matches what is documented in the provider. I would still love to see it fixed in the provider though, as the order from AWS could change at any time.

**Comment by DrFaust92** [comment]
MQ Broker currently keeps the order of endpoints, if error persists please open a new ticket with relevant detailts.
