### ISSUE TITLE
redacted_fields "single_query_argument" for resource aws_wafv2_web_acl_logging_configuration throws an error

### ISSUE THREAD

**Issue by jiwuh** [hashicorp/terraform-provider-aws#14244]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

* Terraform version: 0.13.0
* AWS Provider Version: 2.70.0

### Affected Resource(s)

* aws_wafv2_web_acl_logging_configuration

### Terraform Configuration Files

```hcl
resource "aws_wafv2_web_acl_logging_configuration" "example" {
  log_destination_configs = ["${aws_kinesis_firehose_delivery_stream.example.arn}"]
  resource_arn            = "${aws_wafv2_web_acl.example.arn}"
  redacted_fields {
    single_query_argument {
      name = "username"
    }
  }
}
```
### Expected Behavior
The data field for Query string is selected on the AWS console as shown below:
![image](https://user-images.githubusercontent.com/37252198/87849417-69b63600-c8e0-11ea-80bb-0b58c43ea0cd.png)

### Actual Behavior
The API call breaks, throwing the error shown below:

![image](https://user-images.githubusercontent.com/37252198/87849719-9b300100-c8e2-11ea-84a4-8654d3290077.png)

### Steps to Reproduce

1. `terraform apply`

**Comment by anGie44** [comment]
Hi again @jiwuh! Thanks for creating this issue! Similar to the comment made in #14248, further testing with the API in the context of adding a logging configuration to a WAFv2 WebACL has shown that the current `redacted_fields` block with nested attributes (represented by the `FieldToMatch` object in the AWS SDK https://docs.aws.amazon.com/waf/latest/APIReference/API_LoggingConfiguration.html) is not fully supported by the API, such that in addition to the `single_query_argument` attribute, `all_query_arguments` and `body` are also not supported and thus should not be used when configuring a `redacted_fields` block. 

The linked PR will hopefully address these discrepancies and work-around the API behavior we're seeing. If you have any further questions, please let me know :)

**Comment by jiwuh** [comment]
Thanks for your prompt response @anGie44 . Based on my understanding of your response, single_query_argument is not to be used while configuring a redacted_fields block? Is this correct?

**Comment by anGie44** [comment]
Correct! Only the 4 field types (method, query_string, uri_path, single_header), as seen in the AWS Console with a slightly different naming convention, will work w/o error

**Comment by jiwuh** [comment]
This is noted @anGie44. I'll close this issue then. Thanks again!

**Comment by anGie44** [comment]
Actually let's keep this one open as it's still a valid bug in this resource and we can close it when the fix is merged in :)

**Comment by davidham** [comment]
Hi, just wanted to pipe in and say this issue is still happening, I was not able to set `single_query_argument`. Also, when I set:

```hcl
redacted_fields {
  query_string {}
}
```
the `terraform apply` works, but the field is not shown as set in the console. Setting `all_query_arguments` seems to have no effect. This is under Terraform 0.13 with version 3.15 of the provider. Thanks!
