### ISSUE TITLE
Using the aws_serverlessapplicationrepository_cloudformation_stack resource works the first time, but subsequent updates fail.

### ISSUE THREAD

**Issue by cdhesse** [hashicorp/terraform-provider-aws#16485]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.5

### Affected Resource(s)

aws_serverlessapplicationrepository_cloudformation_stack

### Terraform Configuration Files

```hcl
data aws_serverlessapplicationrepository_application directory_app {
  application_id   = var.app_id
  semantic_version = var.app_semver
}

resource aws_serverlessapplicationrepository_cloudformation_stack directory_index_stack {
  count = var.disabled || ! var.enable_default_directory_index ? 0 : 1
  name  = "${var.stack_name}-${var.stage}-directory-index"

  tags = var.tags

  application_id = data.aws_serverlessapplicationrepository_application.directory_app.application_id
  capabilities   = data.aws_serverlessapplicationrepository_application.directory_app.required_capabilities

  parameters = {
    Version = var.version
  }
}
```

### Expected Behavior

Running 2 times should not cause an error.

### Actual Behavior

Doing a terraform apply the second time results in an error:
Error: error creating Serverless Application Repository CloudFormation Stack (arn:aws:cloudformation:::stack/<stack_name>/) change set: unexpected state 'FAILED', wanted target 'CREATE_COMPLETE'. last error: %!s()

Looking in cloudformation, the change set is Status: Failed, Status Reason: No updates are to be performed.

### Steps to Reproduce

1. `terraform apply` (my example is using Lambda at edge functions if this makes a difference)
2. `terraform apply` a second time

**Comment by anGie44** [comment]
Hi @cdhesse , thank you for raising this issue. To further investigate the behavior you're seeing, do you mind describing what changes in your configuration between the first and second apply? if you have debug logs readily available or can reproduce the behavior in the meantime with the env `TF_LOG=debug`, it would be greatly appreciated to add them to the description when you have a chance :)

**Comment by cdhesse** [comment]
Thanks @anGie44 - the point is nothing is changed from the first run to the second... aka - nothing changed... simply run terraform apply 2x's in a row and i get the error.  The fact that it is saying that the changeset failed due to no changes found, is accurate.  Seems to me that that  the "-no-fail-on-empty-changeset" parameter, which is part of the API is set to "-fail-on-empty-changeset".

**Comment by cdhesse** [comment]
Following up here to provide sample code to re-create this error.

````hcl
terraform {
  required_version = "~> 0.13"
  required_providers {
    aws = "~> 3.18"
  }
}

provider "aws" {
  region = "us-east-1"
}

data aws_serverlessapplicationrepository_application app {
  application_id   = "arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world"
  semantic_version = "1.0.4"
}

resource aws_serverlessapplicationrepository_cloudformation_stack hello_world_stack {
  name = "serverless-hello-world-test"

  application_id = data.aws_serverlessapplicationrepository_application.app.application_id
  capabilities   = data.aws_serverlessapplicationrepository_application.app.required_capabilities
  parameters = {
    IdentityNameParameter: "MyName"
  }
}
````

1.  Run `terraform apply` -> this succeeds
2.  After success, change nothing, simply run `terraform apply` a second time.  This FAILS.

Error
aws_serverlessapplicationrepository_cloudformation_stack.hello_world_stack: Modifying... [id=arn:aws:cloudformation:us-east-1:XXXXXXXXX:stack/serverlessrepo-serverless-hello-world-test/7a6ef230-38a6-11eb-98ff-0ab512dce13f]

Error: error creating Serverless Application Repository CloudFormation Stack (arn:aws:cloudformation:us-east-1:XXXXXXXXX:stack/serverlessrepo-serverless-hello-world-test/7a6ef230-38a6-11eb-98ff-0ab512dce13f) change set: unexpected state 'FAILED', wanted target 'CREATE_COMPLETE'. last error: %!s(<nil>)

**Comment by anGie44** [comment]
Hi @cdhesse, apologies for the delay! Seems this may be a two-part problem but the most straightforward way to work around this in the meantime would be to set `capabilities = ["CAPABILITY_IAM"]` in your config, and that should eliminate the need for the second `terraform apply`.

For more background, it looks like `data.aws_serverlessapplicationrepository_application.app` doesn't return any values in `required_capabilities` and instead the `aws_serverlessapplicationrepository_cloudformation_stack.hello_world_stack` resource returns the value `CAPABILITY_IAM` as seen in this `terraform plan` (after the first `apply`), resulting in a perpetual diff:
```hcl
  # aws_serverlessapplicationrepository_cloudformation_stack.hello_world_stack will be updated in-place
  ~ resource "aws_serverlessapplicationrepository_cloudformation_stack" "hello_world_stack" {
      ~ capabilities     = [
          - "CAPABILITY_IAM",
        ]
        id               = "arn:aws:cloudformation:us-east-1:xxxxxxxxxx:stack/serverlessrepo-serverless-hello-world-test/bbaaf210-38e9-11eb-94f7-0acfa743837d"
        name             = "serverless-hello-world-test"
        tags             = {}
        # (4 unchanged attributes hidden)
    }
```

This implies the AWS Cloudformation API computes the `capabilities` value, even when one is not provided, so that's a bug in the provider such that the `capabilities` field should be considered an `Optional/Computed` not `Required` field.

The second issue regarding the error seen after terraform attempts to `Modify` the resource: it could be a valid error from the AWS Cloudformation API as this troubleshooting error page describes (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html#troubleshooting-errors-no-updates-to-perform). We could follow-up with AWS support to see how they recommend making just a change to the `capabilities` field or mark the field as `ForceNew` as well if we can't update it after creation. 

Hope this helps in the meantime @cdhesse!

**Comment by cdhesse** [comment]
Thanks for the workaround.  Indeed I confirm that hard coding the capabilities to ["CAPABILITY_IAM"] allows it to work on subsequent apply runs.  I thought the point was to grab the required capabilities from the serverless application repo definition in case they get updated from version to version.  Is that not a right understanding?

capabilities   = data.aws_serverlessapplicationrepository_application.app.required_capabilities

**Comment by anGie44** [comment]
hi @cdhesse, indeed in general you could grab the `required_capabilities` attribute from the data-source but it seems in the example that AWS provides, that serverless application doesn't have any set :/ . that field is set to an empty array `[]` in terraform and here's why I'm seeing in the Console (after being redirected from Serverless App Repository page): 
<img width="875" alt="Screen Shot 2020-12-09 at 11 20 08 AM" src="https://user-images.githubusercontent.com/13805595/101657770-449e9d00-3a12-11eb-9108-d26ecb92a842.png">

**Comment by cdhesse** [comment]
So - interesting that there seems to be a second issue.  For applications that require parameters (my real use case, not the hello-world one)... once i hard coded the CAPABILITY_IAM for this stack, I noticed a new bug.  It seems that the parameters are not being persisted.  Terraform refresh pulls back 4 parameters, even though there are 7 parameters in the configuration.  I've not noticed anything strange about the parameters being dropped vs. kept, but something to look into.  I'll try to dig deeper but the result is that this component is still not working for me given this second issue.

**Comment by moko-001** [comment]
Hi,
just checking to see if there have been any updates on this, please?
we are currently facing the exact same issue with using aws_serverlessapplicationrepository_cloudformation_stack, we also use parameters and have not been able to get a second deployment to work.

**Comment by simonhanmer** [comment]
Also seeing this issue.

We've deployed a stack using 

```
resource "aws_serverlessapplicationrepository_cloudformation_stack" "salesforceIntegrationLambda" {
    name            = "salesforceIntegrationLambda"
    application_id  = "arn:aws:serverlessrepo:us-west-2:821825267871:applications/AmazonConnectSalesforceLambda"

    capabilities = [ 
        "CAPABILITY_IAM",
        "CAPABILITY_NAMED_IAM"
    ]

    parameters = {
      ...
   }
}
```

which creates a cloudformation stack called serverlessrepo-salesforceIntegrationLambda.

However, on the second `terraform apply`, we get a failure. Checking CloudTrail, I can see that a `cloudformation.DescribeStacks` API call is failing with the error `Stack with id aws-serverless-repository-salesforceIntegrationLambda does not exist` - it seems to be looking for the wrong stack name?

**Comment by DanyC97** [comment]
following up based on same example provided by @cdhesse , i've run the below and i didn't get the error on 2nd time when run `terraform apply`

```
terraform {
  required_version = "~> 0.13"
  required_providers {
    aws = "~> 3.50.0"
  }
}

provider "aws" {
  region = "us-east-1"
  profile = "xxx"
}

data aws_serverlessapplicationrepository_application app {
  application_id   = "arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world"
  semantic_version = "1.0.4"
}

resource aws_serverlessapplicationrepository_cloudformation_stack hello_world_stack {
  name = "serverless-hello-world-test"

  application_id = data.aws_serverlessapplicationrepository_application.app.application_id
  capabilities = [
        "CAPABILITY_IAM",
        "CAPABILITY_NAMED_IAM"
  ]
  parameters = {
    IdentityNameParameter: "MyName"
  }
}

```

not sure which version @simonhanmer been running with but you can see my aws provider version above. Hope that helps a bit

**Comment by kgns** [comment]
> So - interesting that there seems to be a second issue. For applications that require parameters (my real use case, not the hello-world one)... once i hard coded the CAPABILITY_IAM for this stack, I noticed a new bug. It seems that the parameters are not being persisted. Terraform refresh pulls back 4 parameters, even though there are 7 parameters in the configuration. I've not noticed anything strange about the parameters being dropped vs. kept, but something to look into. I'll try to dig deeper but the result is that this component is still not working for me given this second issue.

I can confirm this problem still exists in the latest version of the provider. As @cdhesse said, if you have more than 4 parameters, somehow the plan only refreshes up to 4 parameters from current stack that exists in AWS, and the rest of the parameters are treated as new, hence a diff is calculated. But when you apply the plan, since the diff that was calculated is not the reality, apply errors out with `change set: unexpected state 'FAILED', wanted target 'CREATE_COMPLETE'. last error: No updates are to be performed` error

**Comment by bobk81** [comment]
[anGie44](https://github.com/anGie44) and [kgns](https://github.com/kgns) I can also confirm this is still a problem. I am deploying "cloudfront-authorization-at-edge" and get the same errors, I also started off with using this option. 

`capabilities   = data.aws_serverlessapplicationrepository_application.app.required_capabilitie`

I then changed it to 

`  
capabilities = [
    "CAPABILITY_IAM",
    "CAPABILITY_RESOURCE_POLICY"
  ]
`
I also checked, and unlike the above suggestion, both capabilities are listed.

![image](https://user-images.githubusercontent.com/72081978/200776404-5909c322-7a42-4e79-9496-d24b5db7ee8b.png)

Please advise if anyone has been able to find a working, workaround for this.

**Comment by troyready** [comment]
I'm pretty sure `NoEcho` CFN parameters are triggering this same error as well:

```
          ~ "ParameterName"        = "****" -> "ValueFromTerraform"
```

Terraform thinks the resource needs to be updated but on apply the CFN change-set reports an error of no changes to be performed.

**Comment by yesteph** [comment]
I confirm Terraform try to update the cloudformation stack but as there is no change, the AWS Cloud formation Change Set is empty then enters in Failed status.

When I look at the Terraform state file, It seems that some credentials parameters are stored with `"****"`

**Comment by taiseii** [comment]
My work around to this issue.
just use the locally stored .json CloudFormation stack with terraform  `aws_cloudformationn_stack` resource. 
Then apply always work fine without destroying the resource.

**Comment by bobk81** [comment]
> My work around to this issue. just use the local .json or .yml CloudFormation template with terraform `aws_cloudformationn_stack` resource. Then `terraform apply` works fine without destroying the CloudFormation stack resource.

I have done the same for the time being. The only problem with this is now I need to have that cloudformation template uploaded to an S3 bucket first, as it is too large. If would be great if it could all work as it is supposed to, but the workaround works for now.

**Comment by Amir-Ahmad** [comment]
My temporary solution for this was to add a tag with a random string. this forces an update on every apply though, so it's not ideal.

```terraform
resource "aws_serverlessapplicationrepository_cloudformation_stack" "some_app" {
  tags = {
    RollMe = random_string.rollme.result
  }
}

resource "random_string" "rollme" {
  length  = 16
  special = false

  keepers = {
    uuid = "${uuid()}"
  }
}
```

**Comment by vgw-chriskruger** [comment]
Very annoying issue.

**Comment by arckdash** [comment]
Experiencing the same issue as everyone else on this thread, has anyone managed to find a workaround for this?

In my case we're using terraform cloud for state management and triggers from GHA.

**Comment by arckdash** [comment]
> My temporary solution for this was to add a tag with a random string. this forces an update on every apply though, so it's not ideal.
> 
> ```terraform
> resource "aws_serverlessapplicationrepository_cloudformation_stack" "some_app" {
>   tags = {
>     RollMe = random_string.rollme.result
>   }
> }
> 
> resource "random_string" "rollme" {
>   length  = 16
>   special = false
> 
>   keepers = {
>     uuid = "${uuid()}"
>   }
> }
> ```

When testing this workaround i get the error:
```
Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ aws_serverlessapplicationrepository_cloudformation_stack.datadog_rds_enhanced
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .tags_all: new element "RollMe" has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```
-_-  any suggestions?

**Comment by tbalzer** [comment]
After some tedious debugging we found two things that don't work as expected here:

1. The terraform state only reflects non-default values of the app parameters, so if any parameters are set to the default value this will conflict as the resource will constantly try to remediate this perceived difference
2. The terraform state has the value of "secret"/NoEcho parameters represented as *s which also leads to constant differences (see https://github.com/hashicorp/terraform-provider-aws/issues/16485#issuecomment-1324478395)

Our solution/workaround/hack:
* Do not set values to the default value, just omit them
* Add secret/NoEcho parameters to the lifecycle `ignore_changes` block (beware if you actually want to change those!)

**Comment by nickjmv** [comment]
@tbalzer, could you provide an example on how to set these in the ignore changes block?
I tried the following but this results in an error.
```
  lifecycle {
    ignore_changes = [
      parameters[0].GoogleAdminEmail
    ]
  }
```

Error:
```
Can't access attributes on a primitive-typed value (string).
```

**Comment by tbalzer** [comment]
@nickjmv This works with string indexes, e.g. `parameters["GoogleAdminEmail"]` works fine

**Comment by Jamsheercheriyampadan** [comment]
@tbalzer This worked .. Thanks.

Only option then is to introduce some randomly generated tag which is ugly but kind-of works  ---> add the below in the same terraform code, where the stack is mentioned


resource "random_id" "force_update" {
  byte_length = 2
}





  tags = {
    force_update = random_id.force_update.hex
  }

**Comment by bendrucker** [comment]
Published https://github.com/hashicorp/terraform-provider-aws/pull/46748 to fix this, sitting in draft until I have a chance to run the acceptance tests. If you're keen to see this fixed please go 👍🏻 the PR to move it up the review queue.

**Comment by YakDriver** [comment]
Apologies for the multi-year delay on this one. Thank you to everyone who kept this issue alive and refined the diagnosis along the way — @cdhesse for the original report, @anGie44 for diagnosing the `capabilities` half of the problem early on, @kgns and @troyready for surfacing the >4-parameter and `NoEcho` symptoms, @tbalzer for the consolidated root-cause analysis that pinpointed both default-value pruning and the `NoEcho` `****` behavior, and @bendrucker for picking up #46748 and authoring the fix. The community workarounds documented along the way (`ignore_changes = [parameters]`, hardcoded `capabilities`) are what kept this resource usable in the interim, and we appreciate it.

#46748 is now moving and addresses all three behaviors:

- Configured parameters that match the application default are no longer pruned from state.
- `NoEcho` parameter values are preserved from configuration rather than stored as `****`.
- `capabilities` is now `Optional`/`Computed` so applications that don't require capabilities can omit the argument.

The resource documentation in that PR also includes recovery procedures for resources that were already affected before the fix.

**Comment by YakDriver** [comment]
For resources already affected (state currently contains `****` for `NoEcho` parameters, or is missing default-matching `parameters` keys) the fix in #46748 alone will not unwedge them — the broken state needs a one-time reconciliation. Two procedures, depending on whether the affected parameter is sensitive:

**Option 1 — state surgery (works for all cases, including `NoEcho`):**

1. Add `lifecycle { ignore_changes = [parameters] }` to the resource temporarily so subsequent plans don't fail on the existing drift.
2. Pull state to a local file:

   ```console
   terraform state pull > stack.tfstate
   ```

3. Edit `stack.tfstate`. Under the affected resource's `instances[].attributes.parameters`, add any missing default-matching keys with the value you have configured, and replace any `****` placeholders with the real configured value. Increment the top-level `serial` field by one.
4. Push the corrected state back:

   ```console
   terraform state push stack.tfstate
   ```

5. Remove the `ignore_changes = [parameters]` lifecycle block.
6. Run `terraform plan` to confirm there is no remaining diff.

**Option 2 — parameter perturbation (non-sensitive parameters only):**

For default-matching parameters that don't control sensitive state (for example a `passwordLength` left at its default), you can briefly perturb the value to force a real CloudFormation change:

1. Temporarily change the affected parameter to a non-default value (for example `passwordLength = "33"`).
2. `terraform apply` — the stack updates and state is repopulated for that parameter.
3. Revert the parameter to its intended value.
4. `terraform apply` again. State is now correct; `terraform plan` should show no diff.

This option is generally not appropriate for `NoEcho` parameters because it would cause an actual change to the underlying secret in AWS.

If neither option is workable, `terraform apply -replace=<resource address>` will destroy and recreate the stack as a last resort.
