### ISSUE TITLE
Issue with Route53 and DNSSEC while the cluster is being undeployed in China

### ISSUE THREAD

**Issue by yaremchuk3** [hashicorp/terraform-provider-aws#22334]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* AWS accounts in China region
* Route53 and DNSSEC

### Debug Output

https://gist.github.com/yaremchuk3/a514fe67dc406a7e405643ba9f7e188a

### Panic Output

`Error: error while force deleting Route53 Hosted Zone (Z02456591M16DHVMZ3XXX), disabling DNSSEC: could not get DNS SEC status for hosted zone (Z02456591M16DHVMZ3XXX): AccessDenied: The operation GetDNSSEC is not available for the current AWS account 897775818260.
	status code: 403, request id: 893b9ef3-0049-4e06-93d2-a858dbafd17e`

### Expected Behavior

Hosted zones in AWS should be deleted successfully.

### Actual Behavior

We use AWS for placing our kubernetes clusters. Every night our test clusters are built and undeployed. About December 10th our jobs for undeploying clusters in China AWS started crashed with error related to DNSSec.
`Error: error while force deleting Route53 Hosted Zone (Z02456591M16DHVMZ3XXX), disabling DNSSEC: could not get DNS SEC status for hosted zone (Z02456591M16DHVMZ3XXX): AccessDenied: The operation GetDNSSEC is not available for the current AWS account 897775818260.
	status code: 403, request id: 893b9ef3-0049-4e06-93d2-a858dbafd17e`

It looks like China hasn't implemented this API yet, but our terraform aws module version expects it.
```
Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding hashicorp/aws versions matching ">= 2.33.*"...
- Finding hashicorp/template versions matching ">= 2.1.2"...
- Installing hashicorp/aws v3.67.0...
- Installed hashicorp/aws v3.67.0 (unauthenticated)
- Installing hashicorp/template v2.1.2...
- Installed hashicorp/template v2.1.2 (unauthenticated)
```
### Steps to Reproduce

In Chinese AWS:
1. `aws route53 get-dnssec --hosted-zone-id hosted_zone_id_here`

### References

* #0000

**Comment by gilesvessey** [comment]
We are running into the same issue in AWS Govcloud regions (Terraform 1.1.7,  AWS provider 3.74). Deleting the zone out of the console works, but this same error message appears when Terraform tries to delete hosted zones.

**Comment by kjenney** [comment]
> We are running into the same issue in AWS Govcloud regions (Terraform 1.1.7, AWS provider 3.74). Deleting the zone out of the console works, but this same error message appears when Terraform tries to delete hosted zones.

I am also experiencing the same issue in GovCloud. It would be very helpful to prioritize this.

**Comment by kjenney** [comment]
Still having this issue in GovCloud. It would be nice to prioritize this.

**Comment by kjenney** [comment]
Still having this issue in GovCloud. It would be nice to prioritize this.  Follwoing up with AWS TAM as this is has been open for entirely too long.

**Comment by kjenney** [comment]
I just ran `terraform destroy` and now it's working in GovCloud. I'm running AWS provider 5.7.0. Hopefully this means this is resolved now.

**Comment by cs-fiscal** [comment]
This issue is still occurring with 5.7.0 through 5.11.0 (latest).  What is the necessary IAM policy update in order to grant the permission to delete?  route53.* does not work but going into the web UI with "administrator" policy permissions works.
