### ISSUE TITLE
[Bug]: aws_wafv2_web_acl is unable to use dynamic block to manage "rule_action_override"

### ISSUE THREAD

**Issue by 88lexd** [hashicorp/terraform-provider-aws#28672]
Related:
- #23390
- #23423
- #23936
- #23992
- #24386
- #27175
- #27273
- #27479
- #28191
- 👉 #28672
- #29012
- #29304
- #30858

### Terraform Core Version

1.3.0

### AWS Provider Version

4.44.0

### Affected Resource(s)

aws_wafv2_web_acl

### Expected Behavior

Certain rule actions I want to set to count mode should work via my dynamic block

### Actual Behavior

Terraform errors out and ends with "This is a bug in the provider, which should be reported in the provider's own issue tracker"

### Relevant Error/Panic Output Snippet

```shell
aws_wafv2_web_acl.regional_waf: Refreshing state... [id=bdb18064-f4b7-4484-ba1b-bfef65760385]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_wafv2_web_acl.regional_waf will be updated in-place
  ~ resource "aws_wafv2_web_acl" "regional_waf" {
        id         = "bdb18064-f4b7-4484-ba1b-bfef65760385"
        name       = "reproduce_bug_test"
        tags       = {}
        # (5 unchanged attributes hidden)

      + rule {
          + name     = "AWSManagedRulesAmazonIpReputationList"
          + priority = 2

          + override_action {

              + none {}
            }

          + statement {

              + managed_rule_group_statement {
                  + name        = "AWSManagedRulesAmazonIpReputationList"
                  + vendor_name = "AWS"

                  + rule_action_override {
                      + name = "AWSManagedIPReputationList"

                      + action_to_use {

                          + count {
                            }
                        }
                    }
                  + rule_action_override {
                      + name = "AWSManagedReconnaissanceList"

                      + action_to_use {

                          + count {
                            }
                        }
                    }
                }
            }

          + visibility_config {
              + cloudwatch_metrics_enabled = false
              + metric_name                = "AWSManagedRulesAmazonIpReputationList"
              + sampled_requests_enabled   = false
            }
        }
      - rule {
          - name     = "AWSManagedRulesKnownBadInputsRuleSet" -> null
          - priority = 1 -> null

          - override_action {

              - none {}
            }

          - statement {

              - managed_rule_group_statement {
                  - name        = "AWSManagedRulesKnownBadInputsRuleSet" -> null
                  - vendor_name = "AWS" -> null

                  - rule_action_override {
                      - name = "Log4JRCE_QUERYSTRING" -> null

                      - action_to_use {

                          - count {
                            }
                        }
                    }
                }
            }

          - visibility_config {
              - cloudwatch_metrics_enabled = false -> null
              - metric_name                = "AWSManagedRulesKnownBadInputsRuleSet" -> null
              - sampled_requests_enabled   = false -> null
            }
        }
      + rule {
          + name     = "AWSManagedRulesKnownBadInputsRuleSet"
          + priority = 1

          + override_action {

              + none {}
            }

          + statement {

              + managed_rule_group_statement {
                  + name        = "AWSManagedRulesKnownBadInputsRuleSet"
                  + vendor_name = "AWS"

                  + rule_action_override {
                      + name = "Log4JRCE_QUERYSTRING"

                      + action_to_use {

                          + count {
                            }
                        }
                    }
                }
            }

          + visibility_config {
              + cloudwatch_metrics_enabled = false
              + metric_name                = "AWSManagedRulesKnownBadInputsRuleSet"
              + sampled_requests_enabled   = false
            }
        }

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Error: Provider produced inconsistent final plan

When expanding the plan for aws_wafv2_web_acl.regional_waf to include new
values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.rule: planned set element
cty.ObjectVal(map[string]cty.Value{"action":cty.ListValEmpty(cty.Object(map[string]cty.Type{"allow":cty.List(cty.Object(map[string]cty.Type{"custom_request_handling":cty.List(cty.Object(map[string]cty.Type{"insert_header":cty.Set(cty.Object(map[string]cty.Type{"name":cty.String,
"value":cty.String}))}))})),
"block":cty.List(cty.Object(map[string]cty.Type{"custom_response":cty.List(cty.Object(map[string]cty.Type{"custom_response_body_key":cty.String,
...
"visibility_config":cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"cloudwatch_metrics_enabled":cty.False,
"metric_name":cty.StringVal("AWSManagedRulesKnownBadInputsRuleSet"),
"sampled_requests_enabled":cty.False})})}) does not correlate with any
element in actual.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Terraform Configuration Files

This is the short version of the Terraform code I have

```terraform
terraform {
  required_version = ">= 1.3"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.44.0"
    }
  }
}

provider "aws" {
  alias  = "regional"
  region = "ap-southeast-2"
}

variable "rulesets" {
  # Using "type any" here for simplicity to reproduce bug
  type = any
  default = [
    {
      rule_name               = "AWSManagedRulesKnownBadInputsRuleSet"
      priority                = 1
      rules_override_to_count = ["Log4JRCE_QUERYSTRING"]
    },
    # {
    #   rule_name               = "AWSManagedRulesAmazonIpReputationList"
    #   priority                = 2
    #   rules_override_to_count = ["AWSManagedIPReputationList", "AWSManagedReconnaissanceList"]
    # }
  ]
}

resource "aws_wafv2_web_acl" "regional_waf" {
  scope = "REGIONAL"

  name        = "reproduce_bug_test"

  default_action {
    allow {}
  }

  #######################
  # Begin Rules
  dynamic "rule" {
    for_each = { for this in var.rulesets : this.rule_name => this }
    content {
      name     = rule.key
      priority = rule.value.priority

      override_action {
        none {}
      }

      statement {
        managed_rule_group_statement {
          name        = rule.key
          vendor_name = "AWS"

          dynamic "rule_action_override" {
            for_each = [for rule_override in rule.value.rules_override_to_count : rule_override]

            content {
              name = rule_action_override.value
              action_to_use {
                count {}
              }
            }
          }
        }
      }

      visibility_config {
        cloudwatch_metrics_enabled = false
        metric_name                = rule.key
        sampled_requests_enabled   = false
      }
    }
  }
  #######################
  # End Rules

  visibility_config {
    cloudwatch_metrics_enabled = true
    metric_name                = "test-waf-metrics"
    sampled_requests_enabled   = true
  }
}
```

### Steps to Reproduce

When I uncomment the variable from my configuration file so the variable looks like this, then Terraform errors out

```terraform
variable "rulesets" {
  # Using "type any" here for simplicity to reproduce bug
  type = any
  default = [
    {
      rule_name               = "AWSManagedRulesKnownBadInputsRuleSet"
      priority                = 1
      rules_override_to_count = ["Log4JRCE_QUERYSTRING"]
    },
    {
      rule_name               = "AWSManagedRulesAmazonIpReputationList"
      priority                = 2
      rules_override_to_count = ["AWSManagedIPReputationList", "AWSManagedReconnaissanceList"]
    }
  ]
}
```

I notice the bug only happens if I am using "rules_override_to_count". Say for example if I have the following variables, I can add/remove as many rules as I want. As long as I am not using the `dynamic "rule_action_override"` block.

```terraform
variable "rulesets" {
  # Using "type any" here for simplicity to reproduce bug
  type = any
  default = [
    {
      rule_name               = "AWSManagedRulesKnownBadInputsRuleSet"
      priority                = 1
      rules_override_to_count = []
    },
    {
      rule_name               = "AWSManagedRulesAmazonIpReputationList"
      priority                = 2
      rules_override_to_count = []
    },
    {
      rule_name               = "AWSManagedRulesBotControlRuleSet"
      priority                = 3
      rules_override_to_count = []
    }
  ]
}
```

### Would you like to implement a fix?

None

**Comment by azt3k** [comment]
I have found I also have this issue when adding new rule managed rule sets to an existing acl, this case I added `AWSManagedRulesAnonymousIpList`

```
  # aws_wafv2_web_acl.web_waf will be updated in-place
  ~ resource "aws_wafv2_web_acl" "web_waf" {
        id          = "028de6e7-0a08-4b34-b8af-e027794232eb"
        name        = "waf_test_web_waf"
        tags        = {
            "Environment" = "waf-test"
            "Project"     = "waf"
        }
        # (6 unchanged attributes hidden)

      - rule {
          - name     = "AWS-AWSManagedRulesATPRuleSet-waf-test" -> null
          - priority = 35 -> null

          - override_action {

              - none {}
            }

          - statement {

              - managed_rule_group_statement {
                  - name        = "AWSManagedRulesATPRuleSet" -> null
                  - vendor_name = "AWS" -> null

                  - managed_rule_group_configs {
                      - login_path = "/Security/login" -> null
                    }
                  - managed_rule_group_configs {
                      - payload_type = "FORM_ENCODED" -> null
                    }
                  - managed_rule_group_configs {

                      - username_field {
                          - identifier = "Email" -> null
                        }
                    }
                  - managed_rule_group_configs {

                      - password_field {
                          - identifier = "Password" -> null
                        }
                    }
                }
            }

          - visibility_config {
              - cloudwatch_metrics_enabled = true -> null
              - metric_name                = "AWS-AWSManagedRulesATPRuleSet-waf-test" -> null
              - sampled_requests_enabled   = true -> null
            }
        }
      + rule {
          + name     = "AWS-AWSManagedRulesATPRuleSet-waf-test"
          + priority = 35

          + override_action {

              + none {}
            }

          + statement {

              + managed_rule_group_statement {
                  + name        = "AWSManagedRulesATPRuleSet"
                  + vendor_name = "AWS"

                  + managed_rule_group_configs {
                      + login_path = "/Security/login"
                    }
                  + managed_rule_group_configs {
                      + payload_type = "FORM_ENCODED"
                    }
                  + managed_rule_group_configs {

                      + username_field {
                          + identifier = "Email"
                        }
                    }
                  + managed_rule_group_configs {

                      + password_field {
                          + identifier = "Password"
                        }
                    }
                }
            }

          + visibility_config {
              + cloudwatch_metrics_enabled = true
              + metric_name                = "AWS-AWSManagedRulesATPRuleSet-waf-test"
              + sampled_requests_enabled   = true
            }
        }
      - rule {
          - name     = "AWS-AWSManagedRulesAmazonIpReputationList-waf-test" -> null
          - priority = 32 -> null

          - override_action {

              - none {}
            }

          - statement {

              - managed_rule_group_statement {
                  - name        = "AWSManagedRulesAmazonIpReputationList" -> null
                  - vendor_name = "AWS" -> null
                }
            }

          - visibility_config {
              - cloudwatch_metrics_enabled = true -> null
              - metric_name                = "AWS-AWSManagedRulesAmazonIpReputationList-waf-test" -> null
              - sampled_requests_enabled   = true -> null
            }
        }
      + rule {
          + name     = "AWS-AWSManagedRulesAmazonIpReputationList-waf-test"
          + priority = 32

          + override_action {

              + none {}
            }

          + statement {

              + managed_rule_group_statement {
                  + name        = "AWSManagedRulesAmazonIpReputationList"
                  + vendor_name = "AWS"
                }
            }

          + visibility_config {
              + cloudwatch_metrics_enabled = true
              + metric_name                = "AWS-AWSManagedRulesAmazonIpReputationList-waf-test"
              + sampled_requests_enabled   = true
            }
        }
      + rule {
          + name     = "AWS-AWSManagedRulesAnonymousIpList-waf-test"
          + priority = 33

          + override_action {

              + none {}
            }

          + statement {

              + managed_rule_group_statement {
                  + name        = "AWSManagedRulesAnonymousIpList"
                  + vendor_name = "AWS"

                  + rule_action_override {
                      + name = "HostingProviderIPList"

                      + action_to_use {

                          + count {
                            }
                        }
                    }
                }
            }

          + visibility_config {
              + cloudwatch_metrics_enabled = true
              + metric_name                = "AWS-AWSManagedRulesAnonymousIpList-waf-test"
              + sampled_requests_enabled   = true
            }
        }
      - rule {
          - name     = "AWS-AWSManagedRulesBotControlRuleSet-waf-test" -> null
          - priority = 36 -> null

          - override_action {

              - none {}
            }

          - statement {

              - managed_rule_group_statement {
                  - name        = "AWSManagedRulesBotControlRuleSet" -> null
                  - vendor_name = "AWS" -> null

                  - rule_action_override {
                      - name = "CategoryContentFetcher" -> null

                      - action_to_use {

                          - count {
                            }
                        }
                    }
                  - rule_action_override {
                      - name = "SignalAutomatedBrowser" -> null

                      - action_to_use {

                          - count {
                            }
                        }
                    }
                  - rule_action_override {
                      - name = "SignalNonBrowserUserAgent" -> null

                      - action_to_use {

                          - count {
                            }
                        }
                    }
                }
            }

          - visibility_config {
              - cloudwatch_metrics_enabled = true -> null
              - metric_name                = "AWS-AWSManagedRulesBotControlRuleSet-waf-test" -> null
              - sampled_requests_enabled   = true -> null
            }
        }
      + rule {
          + name     = "AWS-AWSManagedRulesBotControlRuleSet-waf-test"
          + priority = 36

          + override_action {

              + none {}
            }

          + statement {

              + managed_rule_group_statement {
                  + name        = "AWSManagedRulesBotControlRuleSet"
                  + vendor_name = "AWS"

                  + rule_action_override {
                      + name = "CategoryContentFetcher"

                      + action_to_use {

                          + count {
                            }
                        }
                    }
                  + rule_action_override {
                      + name = "SignalAutomatedBrowser"

                      + action_to_use {

                          + count {
                            }
                        }
                    }
                  + rule_action_override {
                      + name = "SignalNonBrowserUserAgent"

                      + action_to_use {

                          + count {
                            }
                        }
                    }
                }
            }

          + visibility_config {
              + cloudwatch_metrics_enabled = true
              + metric_name                = "AWS-AWSManagedRulesBotControlRuleSet-waf-test"
              + sampled_requests_enabled   = true
            }
        }

        # (14 unchanged blocks hidden)
    }
```

This resulted in the same outcome;

```
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for aws_wafv2_web_acl.web_waf to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .rule: planned set element
```

Terraform v1.3.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.56.0

**Comment by hypsrizzari** [comment]
There are several bugs opened that look related to this issue.  I was in the same boat having to taint the existing resource to get it to apply.  The comment in issue 28191 resolved it for me with AWS provider 4.5x.  Hope it helps.  Kudos to the author.

https://github.com/hashicorp/terraform-provider-aws/issues/28191#issuecomment-1398853194

**Comment by zamirTo1** [comment]
No :(

**Comment by daniel-brown-improving** [comment]
I got my issue resolved with a little help from a guy on Reddit.  Here's a great example using a dynamic block with "rule_action_override".  Thank you Trussworks.  I'm using AWS Provider 5.4.0 and Terraform 1.50.  

Check this out:
https://github.com/trussworks/terraform-aws-wafv2/blob/main/main.tf#L47-L62

**Comment by YakDriver** [comment]
**NOTE:** I cannot reproduce this error after trying various configurations. _**Let us know**_ if this is still a problem! If we don't hear and can't reproduce, we plan to close this on or around **July 20, 2023**. The evidence suggests this is OBE (ie, fixed in the interim).

For more details see #23992 ([comment](https://github.com/hashicorp/terraform-provider-aws/issues/23992#issuecomment-1634920741)).

**Comment by 88lexd** [comment]
I am still facing the same issue by using my test code above to reproduce this issue. I am using the aws provider v5.8.0
```
$ terraform version
Terraform v1.3.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.8.0
```

**Comment by 88lexd** [comment]
Interesting! Works for me using the following versions! will close this issue off thanks!
```
Terraform v1.5.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.8.0
```
