### ISSUE TITLE
[Bug]:  ValidationException: {"ValidationErrorFields":[{"Name":"SourceParameters.DynamoDBStreamParameters","Message":"Missing required parameter."}]}

### ISSUE THREAD

**Issue by sidnhs** [hashicorp/terraform-provider-aws#30773]
### Terraform Core Version

1.3.0

### AWS Provider Version

4.63.0

### Affected Resource(s)

aws_pipes_pipe

### Expected Behavior

There should be a field for specifying additional source parameters apart from the filter criteria

### Actual Behavior

No field to pass additional source parameters

### Relevant Error/Panic Output Snippet

```shell
operation error Pipes: CreatePipe, https response error StatusCode: 400, RequestID: ca5a3264-eacd-4e33-9d3a-bce8bf60b130, ValidationException: {"ValidationErrorFields":[{"Name":"SourceParameters.DynamoDBStreamParameters","Message":"Missing required parameter."}]}
```

### Terraform Configuration Files

```terraform
resource "aws_pipes_pipe" "pipes_pipe_transactional_reporting" {
  name       = "reporting-pipe"
  role_arn   = aws_iam_role.pipes_transactional_reporting_role.arn
  source     = var.source_dynamo_db_table_config.stream_arn
  target     = aws_kinesis_firehose_delivery_stream.to_s3.arn
  enrichment = module.transaction_classifier_lambda.lambda_function_arn

  source_parameters {
    filter_criteria {
      filter{
                pattern = jsonencode({

                    "eventName" : ["INSERT"],
                    "dynamodb" : {
                      "NewImage" : {
                        "status" : {
                          "S" : ["DELIVERED", "FAILED", "SKIPPED"]
                        }
                      }
                    }
                  })
      }

      filter {
              pattern =  jsonencode({
                    "eventName" : ["MODIFY"],
                    "dynamodb" : {
                      "OldImage" : {
                        "status" : {
                          "S" : [{
                            "anything-but" : ["DELIVERED", "FAILED", "SKIPPED"]
                          }]
                        }
                      },
                      "NewImage" : {
                        "status" : {
                          "S" : ["DELIVERED", "FAILED", "SKIPPED"]
                        }
                      }
                    }
                  })
      }
    }
  }
  target_parameters {}
}
```

### Steps to Reproduce

terraform apply

### Would you like to implement a fix?

None

**Comment by jordanfinners** [comment]
This should be fixed by https://github.com/hashicorp/terraform-provider-aws/issues/28153#issuecomment-1516898932

**Comment by lbeltramino-uala** [comment]
I'm having issues because of this bug as well. When is this going to be fixed?

**Comment by naathanbrown** [comment]
Still seeing this issue with DynamoDB stream as input. @tushar-sg are you the same?

**Comment by jordanfinners** [comment]
Are you on the latest terraform version?
There's an example of dynamodb in the tests
https://github.com/hashicorp/terraform-provider-aws/blob/3976e589f9772a637fd86bfe617bd98416231243/internal/service/pipes/pipe_test.go#L2117

**Comment by arshad696** [comment]
Im still seeing the same issue with DynamoDB stream as source with only filter_criteria within the source parameters, but adding the dynamodb_stream_parameters with the starting_position worked for me. 

Tried this on,  TF version 1.4.6 and provider 5.6.2

**Comment by justinretzolk** [comment]
Hi all 👋 Based on some of the more recent replies, this appears to now be resolved. With that in mind, we'll close this issue out. If you experience further issues that seem related to this, please open a new issue so that we can triage it appropriately.
