### ISSUE TITLE
[Bug]: Data aws_lambda_function isn't getting the tags

### ISSUE THREAD

**Issue by LozanoMatheus** [hashicorp/terraform-provider-aws#31497]
### Terraform Core Version

1.3.6

### AWS Provider Version

4.67.0

### Affected Resource(s)

* data `aws_lambda_function`

### Expected Behavior

```
Changes to Outputs:
  + aws_lambda_function = {
      + arn                            = "arn:aws:lambda:<REDACT_AWS_ACCOUNT_REGION>:<REDACT_AWS_ACCOUNT_ID>:function:<REDACT_LAMBDA_NAME>"
    + tags                           = {
        "VAR001" = "VALUE001",
        "VAR002" = "VALUE002"
      }
    }
```

### Actual Behavior

```
Changes to Outputs:
  + aws_lambda_function = {
      + arn                            = "arn:aws:lambda:<REDACT_AWS_ACCOUNT_REGION>:<REDACT_AWS_ACCOUNT_ID>:function:<REDACT_LAMBDA_NAME>"
    + tags                           = {}
```

### Terraform Configuration Files

```hcl
data "aws_lambda_function" "main" {
  function_name = "<REDACT_MY_LAMBDA_NAME>"
  qualifier     = "$LATEST"
}
```

### Steps to Reproduce

```bash
terraform plan

## or

aws lambda get-function --function-name <REDACT_MY_LAMBDA_NAME>
```

### References

* [AWS CLI Get Functions](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/get-function.html)

### Would you like to implement a fix?

No

**Comment by tcharewicz** [comment]
The last version of aws provider, were it was working is 4.22.

**Comment by lovemew67** [comment]
In my case, tags of lambda function with published versions cannot be listed. Those lambda functions without published version still work fine.

**Comment by LozanoMatheus** [comment]
I was just trying to debug this and see the difference between the TF and AWS CLI. I found something that could be the reason.

For TF I first did the `export TF_LOG=TRACE` and for the AWS CLI I added `--debug`

```bash
## TF
export TF_LOG=TRACE
terraform plan

## AWS CLI
aws lambda get-function --function-name <REDACT_MY_LAMBDA_NAME> --debug
```

In the TF code:

```hcl
data "aws_lambda_function" "main" {
  function_name = "<REDACT_MY_LAMBDA_NAME>"
}

output "aws_lambda_function" {
  value = data.aws_lambda_function.main
}
```

The main differences were the `FunctionArn`, `RevisionId`, and `Version`. It seems that TF always adds the `Version` at the end of `FunctionArn` which make the AWS API return `"Tags": null`.

For example, for that code vs AWS CLI calls I had this:

Terraform:
```json
"RevisionId": "602c2b1e-<REDACT_MY_LAMBDA_REVISION_ID>",
"Version": "4",
"FunctionArn": "arn:aws:lambda:<REDACT_MY_AWS_REGION>:<REDACT_MY_AWS_ACCOUNT_ID>:function:<REDACT_MY_LAMBDA_NAME>:4",
```

And for the AWS CLI:

```json
"RevisionId": "5ea092dd-<REDACT_MY_LAMBDA_REVISION_ID>",
"Version": "$LATEST",
"FunctionArn": "arn:aws:lambda:<REDACT_MY_AWS_REGION>:<REDACT_MY_AWS_ACCOUNT_ID>:function:<REDACT_MY_LAMBDA_NAME>",
```

See that the `Version` are different and the TF one has the version at the end of the `FunctionArn`.

I think the issue is how we get the Lambda via Terraform, it's always adding the qualifier. The AWS CLI only returns the tags when you don't pass any qualifier, but in my case, TF didn't return the tags in both cases (with and without the qualifier).

If I compare the results of the CLI and the GUI, I think the AWS CLI is behaving correctly. In the GUI, if you go to your lambda and then to alias or version, it won't have the `Tags` under the tab `Configuration`

**Comment by digitalkaoz** [comment]
bumped into the same error as well, nobody expects that bug, so please get this fixed!

**Comment by datamaker** [comment]
I'm going through the same situation. Is it resolved?

**Comment by jfharden** [comment]
I'm using Provider 5.84.0 and terraform 1.9.6 and this issue is fixed, the data resource correctly receives the tags.

**Comment by RogerJohnSenacor** [comment]
Using provider 6.41.0 and terraform 1.13.4, and getting tags only on some lambdas, but no tags on most, so not fixed. But maybe i have a more complicated setup which might cause timing issues due to number of lambdas (~100):
```
data "aws_lambda_functions" "all" {}

data "aws_lambda_function" "all" {
  count         = length(data.aws_lambda_functions.all.function_names)
  function_name = data.aws_lambda_functions.all.function_names[count.index]
}
```
