### ISSUE TITLE
[Question]: Support 'Argument Syntax' for blocks as described in the 'Attributes as Blocks' documentation?

### ISSUE THREAD

**Issue by Makeshift** [hashicorp/terraform-provider-aws#31982]
### Description

(I would have opened a thread in the forum to ask this question, but it appears the forum is broken due to a CORS issue currently)

I may be misunderstanding the documentation here, but the [Arbitrary Expressions with Argument Syntax](https://developer.hashicorp.com/terraform/language/attr-as-blocks#arbitrary-expressions-with-argument-syntax) section in the [Attributes as Blocks](https://developer.hashicorp.com/terraform/language/attr-as-blocks) page implies that block attributes should be able to be defined as arrays, like so:

```terraform
locals {
    settings = [{
        metrics_enabled = true
        logging_level = "info"
    }]
}

resource "aws_api_gateway_method_settings" "this" {
  ....
  settings = local.settings
}

```

However, this doesn't appear to be the case, as I get `Error: Insufficient settings blocks` and `Unsupported argument: An argument named "settings" is not expected here. Did you mean to define a block of type "settings"?`.

This limitation means that to allow dynamic setting of any attribute supported by, for example `aws_api_gateway_method_settings`, requires something like this:
```terraform
variable "api_settings" {}

resource "aws_api_gateway_method_settings" "api" {
  rest_api_id = aws_api_gateway_rest_api.api.id
  stage_name = aws_api_gateway_deployment.api.stage_name
  method_path = "*/*"
    settings {
        metrics_enabled = lookup(var.api_settings, "metrics_enabled", null)
        logging_level = lookup(var.api_settings, "logging_level", null)
        data_trace_enabled = lookup(var.api_settings, "data_trace_enabled", null)
        throttling_burst_limit = lookup(var.api_settings, "throttling_burst_limit", null)
        throttling_rate_limit = lookup(var.api_settings, "throttling_rate_limit", null)
        caching_enabled = lookup(var.api_settings, "caching_enabled", null)
        cache_ttl_in_seconds = lookup(var.api_settings, "cache_ttl_in_seconds", null)
        cache_data_encrypted = lookup(var.api_settings, "cache_data_encrypted", null)
        require_authorization_for_cache_control = lookup(var.api_settings, "require_authorization_for_cache_control", null)
        unauthorized_cache_control_header_strategy = lookup(var.api_settings, "unauthorized_cache_control_header_strategy", null)
    }
}
```
Which also removes any possibility of creating future-proof support for new attributes being added to the settings block by the provider (and in general is a lot of unnecessary boilerplate).

If I'm not misunderstanding the documentation, is this a case where the provider has to add support for 'attributes as blocks' in order for it to work?

```
Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.3.0
```

### References

[Attributes as Blocks - Terraform Docs](https://developer.hashicorp.com/terraform/language/attr-as-blocks#arbitrary-expressions-with-argument-syntax)

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment]
Hey @Makeshift 👋 Thank you for taking the time to raise this! I think the CORS issue must have been fixed since you raised this, as the forum looks to be functional at this point. Attributes-as-Blocks mode is more of a holdover to help support some resources from the pre- Terraform 0.12 era:

> However, in some cases existing provider features were relying on the conflation of these two concepts in the language of Terraform v0.11 and earlier, using nested block syntax in most cases but using argument syntax to represent explicitly the idea of removing all existing objects of that type, since the absence of any blocks was interpreted as "ignore any existing objects".
>
> The information on this page only applies to certain special arguments that were relying on this usage pattern prior to Terraform v0.12.

Because of this, I don't see a time where the provider teams would intentionally introduce this type of functionality to resources that aren't already utilizing it.

I often see setups like you're describing in modules that are intended to be as flexible as possible. In those cases, I see the pattern that you described (using `lookup()` or `try()` for each available setting) using fairly ubiquitously, so while it does introduce some boilerplate, that would be the path that I would likely take if I were in your situation.

**Comment by Makeshift** [comment]
> Hey @Makeshift 👋 Thank you for taking the time to raise this! I think the CORS issue must have been fixed since you raised this, as the forum looks to be functional at this point. 

Hi @justinretzolk! Indeed, I am able to access the forums now, although I had to do a cache-free refresh to grab a version of the content that wasn't still encountering CORS errors. It appears that your cache-control header is set to instruct browsers to retain cache for 365 days for most of the content, so it may be worth dropping a message to someone able to invalidate the cache in your CDN? (I unfortunately didn't keep a copy of the requests before forcing a refresh, so I'm not sure exactly which file was the culprit)

> I often see setups like you're describing in modules that are intended to be as flexible as possible. In those cases, I see the pattern that you described (using `lookup()` or `try()` for each available setting) using fairly ubiquitously, so while it does introduce some boilerplate, that would be the path that I would likely take if I were in your situation.

I've found in the many modules I've created for use by my team that providing reasonably flexible puzzle pieces that can be glued together without significant Terraform or AWS knowledge is the most efficient way to assist in adopting IaC early in projects, and the block-based paradigm significantly complicates maintenance and makes for an additional learning curve to anyone coming to Terraform from any other language. Not supporting the option for a more familiar approach is unfortunate, but I understand that it is the direction the team has chosen and I thank you for the explanation.
