### ISSUE TITLE
[Bug]: `aws_appstream_stack` user_settings update causes persistent drift

### ISSUE THREAD

**Issue by sarangak** [hashicorp/terraform-provider-aws#39754]
### Terraform Core Version

1.3.7

### AWS Provider Version

5.66.0

### Affected Resource(s)

* aws_appstream_stack shows persistent drift:
  ```
        - user_settings {
            - action     = "AUTO_TIME_ZONE_REDIRECTION" -> null
            - permission = "DISABLED" -> null
          }
  ```

I am guessing this is due to the addition of this field to the API: https://aws.amazon.com/about-aws/whats-new/2024/10/amazon-appstream-2-0-automatic-time-zone-redirection/

### Expected Behavior

We should be able to remove this drift by adding a user_settings block with this value to this resource:
```
resource "aws_appstream_stack" "stack" {
  ...

  user_settings {
    action     = "AUTO_TIME_ZONE_REDIRECTION"
    permission = "DISABLED"
  }

  ...
}

```

### Actual Behavior

Adding this option to the `user_settings` block of the appstream resource does not work (see error below)

This aligns with the [latest provider documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appstream_stack#user_settings) which states:
> user_settings
>  action - (Required) Action that is enabled or disabled. Valid values are CLIPBOARD_COPY_FROM_LOCAL_DEVICE, CLIPBOARD_COPY_TO_LOCAL_DEVICE, FILE_UPLOAD, FILE_DOWNLOAD, PRINTING_TO_LOCAL_DEVICE, DOMAIN_PASSWORD_SIGNIN, or DOMAIN_SMART_CARD_SIGNIN.

### Relevant Error/Panic Output Snippet

```shell
Error: expected action to be one of ["CLIPBOARD_COPY_FROM_LOCAL_DEVICE" "CLIPBOARD_COPY_TO_LOCAL_DEVICE" "FILE_UPLOAD" "FILE_DOWNLOAD" "PRINTING_TO_LOCAL_DEVICE" "DOMAIN_PASSWORD_SIGNIN" "DOMAIN_SMART_CARD_SIGNIN"], got AUTO_TIME_ZONE_REDIRECTION
```

### Terraform Configuration Files

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {}

resource "aws_appstream_stack" "test" {
  name         = "appstream-test"

  user_settings {
    action     = "AUTO_TIME_ZONE_REDIRECTION"
    permission = "DISABLED"
  }
}
```

### Steps to Reproduce

1. Run terraform plan and observe error.

### References

https://aws.amazon.com/about-aws/whats-new/2024/10/amazon-appstream-2-0-automatic-time-zone-redirection/

### Would you like to implement a fix?

No

**Comment by sarangak** [comment]
Actually this seems to have been fixed by updating to a newer version of the AWS provider.

**Comment by bisspector** [comment]
> Actually this seems to have been fixed by updating to a newer version of the AWS provider.

Which version have you updated to? For me updating to the latest 5.72.1 did not fix the issue.

**Comment by sarangak** [comment]
> > Actually this seems to have been fixed by updating to a newer version of the AWS provider.
> 
> Which version have you updated to? For me updating to the latest 5.72.1 did not fix the issue.

@bisspector I updated to 5.72.  Did you add the `user_settings` block to your `aws_appstream_stack` resources?
```
  user_settings {
    action     = "AUTO_TIME_ZONE_REDIRECTION"
    permission = "DISABLED"
  }
```

**Comment by bisspector** [comment]
@sarangak Okay I see, it looks like this user setting is not included in the documentation, but still works if you include it in code. Thanks, this helped.

**Comment by sarangak** [comment]
> @sarangak Okay I see, it looks like this user setting is not included in the documentation, but still works if you include it in code. Thanks, this helped.

@bisspector I agree.  Created https://github.com/hashicorp/terraform-provider-aws/issues/39792 to update the documentation.
