### ISSUE TITLE
iam_policy and aws_iam_policy_attachment ordering

### ISSUE THREAD

**Issue by ablackrw** [hashicorp/terraform-provider-aws#8629]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
terraform -v
Terraform v0.11.13
+ provider.aws v2.10.0
```

### Affected Resource(s)

* aws_iam_policy
* aws_iam_policy_attachment

### Terraform Configuration Files

iam_policy.tf:
```hcl
resource "aws_iam_policy" "Example" {
    name        = "Example"
    path        = "/"
    description = "Trivial policy. Terraform managed. "
    policy      = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*"
    }
  ]
}
POLICY
}
```

iam_roles.tf:
```hcl
resource "aws_iam_role" "Example" {
    name               = "Example"
    path               = "/"
    assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::${data.aws_caller_identity.current.account_id}:saml-provider/provider"
      },
      "Action": "sts:AssumeRoleWithSAML",
      "Condition": {
        "StringEquals": {
          "SAML:aud": "https://signin.aws.amazon.com/saml"
        }
      }
    }
  ]
}
POLICY
}
```

policy_attachment.tf:
```hcl
resource "aws_iam_policy_attachment" "Example-policy-attachment" {
    name       = "Example-policy-attachment"
    policy_arn = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:policy/Example"
    groups     = []
    users      = []
    roles      = ["${aws_iam_role.Example.name}]
}
```

### Expected Behavior

* Prior to destroying the `aws_iam_policy.Example` resource, terraform should destroy the `aws_iam_policy_attachment.Example-policy-attachment` resource.
* After creating the `aws_iam_policy.Example` resource, the `aws_iam_policy_attachment.Example-policy-attachment` resource should be (re)created.

### Actual Behavior

Assorted errors, including the following
```
* aws_iam_policy.Example (destroy): 1 error(s) occurred:

* aws_iam_policy.Example: Error deleting IAM policy arn:aws:iam::${data.aws_caller_identity.current.account_id}:policy/Example: DeleteConflict: Cannot delete a policy attached to entities.
	status code: 409, request id: <uuid>
```

```
* aws_iam_policy_attachment.Example-policy-attachment: 1 error(s) occurred:

* aws_iam_policy_attachment.Example-policy-attachment: [WARN] Error attaching policy with IAM Policy Attachment Example-policy-attachment:
– NoSuchEntity: Policy arn:aws:iam::${data.aws_caller_identity.current.account_id}:policy/Example does not exist or is not attachable.
	status code: 404, request id: <uuid>
```

### Steps to Reproduce

1. `terraform plan -out=tf.plan`
1. `terraform apply "tf.plan"`
1. Second error may be encountered (not tested). Repeat plan/apply if this happens.
1. Modify the description of `aws_iam_policy.Example` (ie 'custom policy. Terraform managed').
1. `terraform plan -out=tf.plan`
1. `terraform apply "tf.plan"`
1. First error message will be encountered.
1. Manually delete the association between `aws_iam_policy.Example` and `aws_iam_role.Example` in the IAM console.
1. `terraform plan -out=tf.plan`
1. `terraform apply "tf.plan"`
1. First error message will be encountered after `aws_iam_policy_attachment.Example-policy-attachment` is recreated.
1. Manually delete the association between `aws_iam_policy.Example` and `aws_iam_role.Example` _and_ the `aws_iam_policy.Example` policy in the IAM console.
1. `terraform plan -out=tf.plan`
1. `terraform apply "tf.plan"`
1. Second error message will be encountered, but `aws_iam_role.Example` will be recreated.
1. `terraform plan -out=tf.plan`
1. `terraform apply "tf.plan"`
1. Apply will be performed successfully.

**Comment by dboeke** [comment]
I have encountered the same issue.  Has this been resolved in later versions?

**Comment by berney** [comment]
It's still happening in recent versions.

```
Error: Error deleting IAM policy arn:aws:iam::<snip>: DeleteConflict: Cannot delete a policy attached to entities.
        status code: 409, request id: <snip?
```

```
$ terraform version
Terraform v0.12.24
+ provider.aws v2.60.0
+ provider.random v2.2.1
```

**Comment by twnbay78** [comment]
I can confirm this is still an issue

Error: Error deleting IAM policy arn:aws:iam::<acc_id>:policy/<policy_name>: DeleteConflict: Cannot delete a policy attached to entities.

	status code: 409, request id: <req_id>

**Comment by RamezWasfy** [comment]
I am still getting the same issue even with newer versions
```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.16.0
```

**Comment by rkitron** [comment]
Hi,

The issue you encounter is because there is no link between the attachment resource and the policy resource, so Terraform see no dependency and then delete the policy before its detachment from the IAM Role.

If you want to solve this, replace the policy_arn in aws_iam_policy_attachment by aws_iam_policy.Example.arn

Hope it helps,

rkitron

**Comment by iaminov** [comment]
> Hi,
> 
> The issue you encounter is because there is no link between the attachment resource and the policy resource, so Terraform see no dependency and then delete the policy before its detachment from the IAM Role.
> 
> If you want to solve this, replace the policy_arn in aws_iam_policy_attachment by aws_iam_policy.Example.arn
> 
> Hope it helps,
> 
> rkitron

I am having the same issue regardless of doing this

**Comment by YakDriver** [comment]
Using this configuration, I was able to perform all the steps without errors. **NOTE:** As mentioned by @rkitron, the `policy_arn` refers to `aws_iam_policy.test.arn`. This is important.

```terraform
data "aws_caller_identity" "current" {}

resource "aws_iam_policy" "test" {
  name        = "tf-acc-5128220496"
  path        = "/"
  description = "Trivial policy 2."
  policy      = <<POL
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*"
    }
  ]
}
POL
}

resource "aws_iam_role" "test" {
  name               = "tf-acc-5128220496"
  path               = "/"
  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::${data.aws_caller_identity.current.account_id}:saml-provider/provider"
      },
      "Action": "sts:AssumeRoleWithSAML",
      "Condition": {
        "StringEquals": {
          "SAML:aud": "https://signin.aws.amazon.com/saml"
        }
      }
    }
  ]
}
POLICY
}

resource "aws_iam_policy_attachment" "test" {
  name       = "tf-acc-5128220496"
  policy_arn = aws_iam_policy.test.arn
  groups     = []
  users      = []
  roles      = [aws_iam_role.test.name]
}
```

1. Apply
2. Update `description`
3. Apply (fine, no errors, 2 replaced)
4. Delete association in console
5. Apply (fine, no errors, 1 created)
